#!/usr/bin/env python3
"""check_exams.py — verify that exam questions are answerable.

Exam pages generated by lesson-builder embed a `questionBank` JS object. Each
question has `question`, `questionThai`, `options[]`, `correct` (index), and
`explanation`. This script catches the common authoring bugs that ship:

  1. Truncated question text — ends with `...`, `?`, or contains an unfilled
     placeholder like `{word}`, `{{...}}`, or `undefined`.
  2. Options list with <2 real entries, duplicates, or empty strings.
  3. `correct` index out of range, or of wrong type.
  4. `correct` option and `explanation` disagree — e.g. the explanation quotes
     a string that doesn't match options[correct], suggesting the index is off.
  5. Identical options (aside from the correct one) — makes question trivial or
     broken depending on intent.
  6. Question text doesn't seem to have a determinate answer — e.g. question
     asks "Which is correct?" with no context, or options are all plausible.
     This class of problem is SEMANTIC and can't be caught by code — the script
     emits a review batch (JSON) so the skill/agent can read each question and
     flag it.

Usage:
    python scripts/check_exams.py HTML/path/to/course
    python scripts/check_exams.py HTML/path/to/course --review-out review.json
    python scripts/check_exams.py HTML/path/to/course --json

Exit codes:
  0 — no structural issues
  1 — one or more structural issues
  2 — invocation error
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Grab the `const questionBank = { ... };` block. We then parse it as JSON
# after stripping the `const questionBank = ` prefix and trailing `;`.
# questionBank values can legally contain nested objects but no JS-only
# features (the generator emits pure JSON-like literals via json.dumps).
BANK_RE = re.compile(
    r"const\s+questionBank\s*=\s*(\{.*?\})\s*;",
    re.DOTALL,
)

# Heuristics for truncated / unfilled question text.
SUSPECT_PATTERNS = [
    (re.compile(r"\{[a-zA-Z_][a-zA-Z0-9_]*\}"),      "unfilled placeholder like {word}"),
    (re.compile(r"\{\{.*?\}\}"),                       "unfilled template placeholder {{...}}"),
    (re.compile(r"\bundefined\b"),                     "contains 'undefined'"),
    (re.compile(r"\bnull\b"),                          "contains 'null'"),
    (re.compile(r"\.\.\.\s*\?*\s*$"),                  "ends with '...'"),
    (re.compile(r'""\s*\?'),                           'contains empty quoted "" before ?'),
    (re.compile(r"^\s*\?+\s*$"),                       "only punctuation"),
]


def extract_bank(html_text: str) -> dict | None:
    m = BANK_RE.search(html_text)
    if not m:
        return None
    raw = m.group(1)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # The generator should emit valid JSON, but fall back to a lenient
        # parse by stripping trailing commas.
        cleaned = re.sub(r",(\s*[}\]])", r"\1", raw)
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError as e:
            sys.stderr.write(f"WARN: could not parse questionBank ({e})\n")
            return None


def find_issues(question: dict) -> list[str]:
    issues: list[str] = []

    q = question.get("question")
    opts = question.get("options")
    correct = question.get("correct")
    explanation = question.get("explanation", "") or ""

    # 1. Question structure
    if not isinstance(q, str) or not q.strip():
        issues.append("question text is missing or empty")
        return issues
    for pat, desc in SUSPECT_PATTERNS:
        if pat.search(q):
            issues.append(f"question looks truncated/unfilled: {desc}")

    # 2. Options
    if not isinstance(opts, list):
        issues.append("options is not a list")
        return issues
    cleaned = [o for o in opts if isinstance(o, str) and o.strip()]
    if len(cleaned) < 2:
        issues.append(f"fewer than 2 real options ({len(cleaned)})")
    if len(set(cleaned)) != len(cleaned):
        dupes = [o for o in cleaned if cleaned.count(o) > 1]
        issues.append(f"duplicate options: {sorted(set(dupes))[:3]}")
    for i, o in enumerate(opts):
        if not isinstance(o, str) or not o.strip():
            issues.append(f"option {i} is empty/missing")
        else:
            for pat, desc in SUSPECT_PATTERNS:
                if pat.search(o):
                    issues.append(f"option {i} looks unfilled: {desc}")

    # 3. Correct index
    if not isinstance(correct, int):
        issues.append(f"correct is not an int ({type(correct).__name__})")
    elif not (0 <= correct < len(opts)):
        issues.append(f"correct={correct} is out of range (0..{len(opts)-1})")
    else:
        correct_text = opts[correct]
        # 4. Explanation / correct-option agreement.
        # Heuristic: the explanation commonly quotes the correct answer.
        # Ignore quoted strings that also appear in the QUESTION (those are
        # just restating the vocab term being defined).
        quoted = re.findall(r'"([^"]{2,})"', explanation)
        q_lower = q.lower()
        quoted_not_in_question = [s for s in quoted if s.strip().lower() not in q_lower]
        if quoted_not_in_question:
            opt_lower = [o.strip().lower() for o in opts if isinstance(o, str)]
            matched_any = any(
                s.strip().lower() in o or o in s.strip().lower()
                for s in quoted_not_in_question for o in opt_lower
            )
            if not matched_any:
                issues.append(
                    f"explanation quotes {quoted_not_in_question[:2]} but none match any option "
                    f"(correct={correct!r} -> {correct_text!r})"
                )

    return issues


def walk_bank(bank: dict):
    """Yield (category, difficulty, index, question_dict)."""
    for cat, diffs in bank.items():
        if not isinstance(diffs, dict):
            continue
        for diff, questions in diffs.items():
            if not isinstance(questions, list):
                continue
            for i, q in enumerate(questions):
                if isinstance(q, dict):
                    yield cat, diff, i, q


def scan_file(html_file: Path) -> dict:
    text = html_file.read_text(encoding="utf-8", errors="replace")
    bank = extract_bank(text)
    result = {
        "file": str(html_file),
        "parsed": bank is not None,
        "total_questions": 0,
        "issues": [],        # structural
        "review_items": [],  # for semantic review
    }
    if not bank:
        return result
    for cat, diff, i, q in walk_bank(bank):
        result["total_questions"] += 1
        found = find_issues(q)
        if found:
            result["issues"].append({
                "category": cat, "difficulty": diff, "index": i,
                "question": q.get("question"),
                "problems": found,
            })
        # Always add to review batch — semantic check runs on everything.
        result["review_items"].append({
            "file": html_file.name,
            "category": cat,
            "difficulty": diff,
            "index": i,
            "question": q.get("question"),
            "question_thai": q.get("questionThai"),
            "options": q.get("options"),
            "correct_index": q.get("correct"),
            "correct_text": q.get("options", [None] * 10)[q.get("correct", -1)]
                            if isinstance(q.get("options"), list) and
                               isinstance(q.get("correct"), int) and
                               0 <= q.get("correct") < len(q.get("options")) else None,
            "explanation": q.get("explanation"),
        })
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description="Verify exam questions are answerable")
    ap.add_argument("course_dir", help="Directory containing *exam*.html files")
    ap.add_argument(
        "--review-out",
        default=None,
        help="Write a JSON file of all questions for semantic review by an LLM.",
    )
    ap.add_argument(
        "--json",
        action="store_true",
        help="Emit a JSON report on stdout instead of human-readable text.",
    )
    args = ap.parse_args()

    course_dir = Path(args.course_dir)
    if not course_dir.is_dir():
        print(f"ERROR: {course_dir} is not a directory", file=sys.stderr)
        return 2

    exam_files = sorted(course_dir.rglob("*exam*.html"))
    if not exam_files:
        print(f"WARN: no *exam*.html files under {course_dir}", file=sys.stderr)
        return 0

    all_results = []
    all_review = []
    total_issues = 0
    total_questions = 0

    for ef in exam_files:
        r = scan_file(ef)
        all_results.append(r)
        all_review.extend(r["review_items"])
        total_questions += r["total_questions"]
        total_issues += len(r["issues"])

    if args.json:
        print(json.dumps({
            "summary": {
                "files": len(exam_files),
                "questions": total_questions,
                "structural_issues": total_issues,
            },
            "results": all_results,
        }, indent=2, ensure_ascii=False))
    else:
        for r in all_results:
            if not r["parsed"]:
                print(f"\n[{Path(r['file']).name}] FAILED TO PARSE questionBank")
                continue
            if r["issues"]:
                print(f"\n[{Path(r['file']).name}] {len(r['issues'])} issue(s) "
                      f"across {r['total_questions']} questions:")
                for item in r["issues"]:
                    print(f"  {item['category']}/{item['difficulty']} #{item['index']}: "
                          f"{item['question']!r}")
                    for p in item["problems"]:
                        print(f"     - {p}")

        print(
            f"\nSummary: {len(exam_files)} exam files, {total_questions} questions, "
            f"{total_issues} structural issues"
        )

    if args.review_out:
        out = Path(args.review_out)
        out.write_text(
            json.dumps(all_review, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print(f"\nWrote {len(all_review)} questions to {out} for semantic review.")
        print("Next step: read the JSON and verify each question's options include "
              "a clearly-correct answer that actually satisfies the question.")

    return 1 if total_issues else 0


if __name__ == "__main__":
    sys.exit(main())
